name: FTP Deployment

on:
  push:
    branches:
      - main  # WICHTIG: Prüfe, ob dein Branch wirklich 'main' heißt (sonst 'master')

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Code auschecken
        uses: actions/checkout@v4

      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.GOKERTECH }}
          username: ${{ secrets.GOKERTECH }}
          password: ${{ secrets.GOKERTECH }}
          server-dir: /htdocs/
          protocol: ftp
          port: 21
